version: '3.9'

services:
  db:
    image: postgres:17-alpine
    container_name: rental_pg
    environment:
      POSTGRES_DB: rental
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data   # <-- this mounts your CSV folder

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
